import streamlit as st
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from google import genai
from google.genai import types
import re
import streamlit.components.v1 as components
import base64
from datetime import datetime

# ==========================================
# CẤU HÌNH GIAO DIỆN CHÍNH
# ==========================================
st.set_page_config(page_title="LINANCE TERMINAL", page_icon="CORE", layout="centered")

# ==========================================
# 1. KHAI BÁO CÁC HÀM TIỆN ÍCH, UI & AI SKILLS
# ==========================================
def render_copy_button(text_to_copy):
    """Hàm tạo nút sao chép bằng HTML/JS nhúng, mã hóa Base64 để tránh lỗi ký tự."""
    text_b64 = base64.b64encode(text_to_copy.encode('utf-8')).decode('utf-8')
    html_code = f"""
    <body style="margin: 0; padding: 0; overflow: hidden; background-color: transparent;">
        <style>
        .copy-btn {{
            background-color: transparent;
            color: #0A84FF;
            border: 1px solid rgba(10, 132, 255, 0.5);
            border-radius: 6px;
            padding: 6px 12px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: bold;
            cursor: pointer;
            transition: all 0.3s ease;
            display: inline-flex;
            align-items: center;
            justify-content: center;
        }}
        .copy-btn:hover {{
            background-color: #0A84FF;
            color: #FFFFFF;
            box-shadow: 0 0 10px rgba(10, 132, 255, 0.4);
            border: 1px solid #0A84FF;
        }}
        </style>
        <button class="copy-btn" id="copyBtn">COPY PLAN</button>
        <script>
        document.getElementById("copyBtn").addEventListener("click", function() {{
            const decodedText = decodeURIComponent(escape(window.atob('{text_b64}')));
            navigator.clipboard.writeText(decodedText).then(function() {{
                document.getElementById("copyBtn").innerText = "✅ COPIED!";
                setTimeout(() => document.getElementById("copyBtn").innerText = "COPY PLAN", 2000);
            }});
        }});
        </script>
    </body>
    """
    return html_code

def generate_professional_report(ai_content):
    """Đóng gói nội dung AI thành tệp Báo cáo chuẩn định dạng tài liệu tổ chức."""
    current_time = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    html_content = ai_content.replace('\n', '<br>').replace('**', '<b>')
    html_content = re.sub(r'\*(.*?)\*', r'<i>\1</i>', html_content)
    
    report_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>LINANCE Quantitative Report</title>
        <style>
            body {{ font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px 20px; }}
            .header {{ border-bottom: 2px solid #0A84FF; padding-bottom: 10px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: baseline; }}
            .logo {{ font-size: 24px; font-weight: 900; color: #0B0F17; letter-spacing: 2px; }}
            .logo span {{ color: #0A84FF; }}
            .timestamp {{ font-size: 12px; color: #666; font-family: monospace; }}
            .content {{ font-size: 14px; text-align: justify; }}
            .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 10px; color: #999; text-align: center; font-style: italic; }}
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo">LINANCE<span>.CORE</span></div>
            <div class="timestamp">Issued: {current_time}</div>
        </div>
        <div class="content">
            {html_content}
        </div>
        <div class="footer">
            CONFIDENTIAL REPORT. Generated by LINANCE Quantitative AI System.<br>
            Disclaimer: Bản báo cáo này được tạo tự động bởi thuật toán định lượng. Nhà đầu tư tự chịu trách nhiệm với quyết định giải ngân.
        </div>
    </body>
    </html>
    """
    return report_html

@st.cache_data(ttl=600)
def load_all_sheets():
    try:
        scopes = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
        creds_dict = dict(st.secrets["gcp_service_account"])
        creds = Credentials.from_service_account_info(creds_dict, scopes=scopes)
        client = gspread.authorize(creds)
        
        spreadsheet = client.open("RS_DATA") 
        all_data = {}
        for ws in spreadsheet.worksheets():
            records = ws.get_all_records(value_render_option='UNFORMATTED_VALUE')
            if records:
                all_data[ws.title] = pd.DataFrame(records)
        return all_data
    except Exception as e:
        st.error(f"SYSTEM ERROR (DATA_LOAD): {e}")
        return {}

# ==========================================
# 2. HÀM GIAO DIỆN HỒ SƠ SỨC KHỎE ĐÃ ĐỒNG BỘ ĐỊNH DẠNG
# ==========================================
def render_rpg_card(ticker: str, df_rs: pd.DataFrame, df_ta: pd.DataFrame = None):
    stock_rs = df_rs[df_rs['Mã CK'] == ticker]
    if stock_rs.empty:
        st.warning(f"Mã cổ phiếu {ticker} chưa có dữ liệu trong hệ thống.")
        return
        
    data = stock_rs.iloc[0].to_dict()
    
    def format_vn(val):
        try:
            if pd.isna(val): return "N/A"
            v = float(val)
            if v.is_integer(): return str(int(v))
            return f"{v:.2f}".replace('.', ',')
        except:
            return str(val)

    display_pe = format_vn(data.get('P/E', 'N/A'))
    display_pb = format_vn(data.get('P/B', 'N/A'))
    display_roe = format_vn(data.get('ROE (%)', 'N/A'))
    
    try:
        current_price = float(data.get('Giá', 0))
        display_price = f"{current_price:,.0f} VNĐ".replace(',', '.')
    except:
        display_price = "N/A"
    
    atk_score = int(data.get('RS_1M', 50))
    mp_score = int(data.get('MFI_14', 50))
    tech_score = data.get('Tech_Score', 0)
    
    def_score = 50
    if df_ta is not None and not df_ta.empty and ticker in df_ta['Mã CK'].values:
        ta_data = df_ta[df_ta['Mã CK'] == ticker].iloc[0].to_dict()
        if "TRÊN Mây" in str(ta_data.get('Trạng Thái Mây', '')): def_score += 30
        elif "DƯỚI Mây" in str(ta_data.get('Trạng Thái Mây', '')): def_score -= 20
        
    try:
        if float(data.get('ROE (%)', 0)) > 15: def_score += 20
    except: pass

    int_score = 50
    try:
        pe_f = float(data.get('P/E', 0))
        if 0 < pe_f < 15: int_score += 20
        elif pe_f > 25 or pe_f < 0: int_score -= 20
        
        pb_f = float(data.get('P/B', 0))
        if 0 < pb_f < 1.5: int_score += 20
        elif pb_f > 3.0: int_score -= 20
        
        debt_f = float(data.get('Nợ/Vốn Chủ', 0))
        if 0 <= debt_f < 1.0: int_score += 10
        elif debt_f > 2.0: int_score -= 10
    except: pass

    atk_score = min(max(atk_score, 0), 100)
    mp_score = min(max(mp_score, 0), 100)
    def_score = min(max(def_score, 0), 100)
    int_score = min(max(int_score, 0), 100)

    if tech_score >= 6: tier, t_col = "S-TIER", "#FFD700"
    elif tech_score >= 3: tier, t_col = "A-TIER", "#00FF00"
    elif tech_score >= 0: tier, t_col = "B-TIER", "#0A84FF"
    else: tier, t_col = "C-TIER", "#FF3A3A"

    industry = str(data.get('Ngành', ''))
    if "Ngân hàng" in industry: rpg_class = "TANKER (Phòng thủ)"
    elif "Chứng khoán" in industry: rpg_class = "ASSASSIN (Đột phá)"
    elif "Công nghệ" in industry: rpg_class = "MAGE (Công nghệ)"
    elif "Bất động sản" in industry: rpg_class = "BERSERKER (Chu kỳ)"
    else: rpg_class = "RANGER (Linh hoạt)"

    st.markdown(f"""
    <div style="background: var(--glass-bg); border: 1px solid var(--glass-border); border-radius: 18px; padding: 20px; margin-bottom: 20px;">
        <h3 style="margin:0; color:#FFF;">[{ticker}] - {rpg_class}</h3>
        <p style="color:{t_col}; font-weight:bold; font-size:18px;">XẾP HẠNG: {tier}</p>
        <hr style="border-color: rgba(255,255,255,0.1); margin: 10px 0;">
    """, unsafe_allow_html=True)
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown(f"**ATK (Tấn công - Sức mạnh giá):** {atk_score}")
        st.progress(atk_score / 100)
        
        st.markdown(f"**MP (Mana - Dòng tiền):** {mp_score}")
        st.progress(mp_score / 100)
        
        st.markdown(f"**GIÁ HIỆN TẠI:** {display_price}")

    with col2:
        st.markdown(f"**DEF (Phòng thủ - Xu hướng):** {def_score}")
        st.progress(def_score / 100)
        
        st.markdown(f"**INT (Trí tuệ - Định giá):** {int_score}")
        st.progress(int_score / 100)
        
        st.markdown(f"**THÔNG SỐ:** P/E: {display_pe} | P/B: {display_pb} | ROE: {display_roe}%")
        
    st.markdown("</div>", unsafe_allow_html=True)

def search_internet(query: str) -> str:
    from duckduckgo_search import DDGS
    try:
        results = DDGS().text(query, max_results=3, region='vn-tz')
        if not results: return "Hệ thống không tìm thấy thông tin phù hợp trên Internet."
        formatted_results = [f"- Tiêu đề: {r['title']}\n  Nội dung: {r['body']}\n  Nguồn: {r['href']}" for r in results]
        return "\n".join(formatted_results)
    except Exception as e:
        return f"SYSTEM ERROR (NETWORK): {e}"

def get_live_stock_data(ticker: str) -> str:
    import yfinance as yf
    try:
        ticker = ticker.strip().upper()
        yf_ticker = f"{ticker}.VN" if not ticker.endswith(".VN") else ticker
        stock = yf.Ticker(yf_ticker)
        
        current_price = stock.fast_info['lastPrice']
        if current_price < 1000: current_price *= 1000
        
        # TÍNH TOÁN KHỐI LƯỢNG ĐỘT BIẾN REAL-TIME
        hist = stock.history(period="1mo")
        if not hist.empty and len(hist) > 0:
            current_vol = hist['Volume'].iloc[-1]
            avg_vol_20 = hist['Volume'].mean()
            surge_ratio = (current_vol / avg_vol_20) * 100 if avg_vol_20 > 0 else 0
            vol_info = f"Khối lượng phiên nay: {current_vol:,.0f} | KL Trung bình 20 phiên: {avg_vol_20:,.0f} | Mức độ đột biến: {surge_ratio:.1f}%"
        else:
            vol_info = "Không trích xuất được dữ liệu khối lượng."
            
        return f"[SYSTEM REAL-TIME UPDATE] Mã: {ticker} | Giá: {current_price:,.0f} VNĐ | {vol_info}."
    except Exception as e:
        return f"Hệ thống không thể truy xuất dữ liệu realtime cho {ticker}. Lỗi: {e}"

def draw_technical_chart(ticker: str) -> str:
    """MUST call this tool to execute Python code that draws the interactive line chart for the stock when user asks for 'đồ thị', 'biểu đồ', 'chart'.
    Args:
        ticker: The 3-letter stock symbol (e.g., HPG, SSI)
    """
    return f"[SYSTEM CHART COMMAND TRIGGERED] Hãy xác nhận bằng văn bản rằng đồ thị kỹ thuật mã {ticker} đang được hiển thị ngay bên dưới đoạn hội thoại."

# ==========================================
# 3. KHỞI TẠO BỘ NHỚ TRUNG TÂM
# ==========================================
dict_dfs = load_all_sheets()
API_KEY = st.secrets["GEMINI_API_KEY"]

# ==========================================
# 4. GIAO DIỆN CHÍNH & CSS
# ==========================================
st.markdown("""
<style>
    :root {
        --ios-radius: 18px;
        --ai-accent: #0A84FF; 
        --ai-glow: rgba(10, 132, 255, 0.3);
        --glass-bg: rgba(128, 128, 128, 0.08); 
        --glass-border: rgba(128, 128, 128, 0.2);
    }
    .main-header { padding: 30px 20px; margin-bottom: 20px; text-align: center; border-bottom: 1px solid var(--glass-border); background: transparent; }
    .main-header h1 { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-weight: 800 !important; letter-spacing: 2px; margin-bottom: 8px; font-size: 32px !important; }
    .main-header p { font-family: "Courier New", Courier, monospace; font-weight: 600; letter-spacing: 3px; text-transform: uppercase; font-size: 12px; color: var(--ai-accent); }
    div[data-testid="stChatMessage"] { background-color: var(--glass-bg); border-radius: var(--ios-radius); border: 1px solid var(--glass-border); padding: 15px; backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); margin-bottom: 15px; }
    .stChatInput { border-radius: var(--ios-radius) !important; border: 1.5px solid var(--ai-accent) !important; box-shadow: 0 0 15px var(--ai-glow) !important; transition: all 0.3s ease; }
    div.stButton > button { background-color: transparent !important; color: #10B981 !important; font-weight: 700 !important; font-family: 'JetBrains Mono', monospace; font-size: 11px; letter-spacing: 0.5px; border-radius: 6px !important; border: 1px solid rgba(16, 185, 129, 0.5) !important; transition: all 0.3s ease; padding: 4px 12px; }
    div.stButton > button:hover { background-color: #10B981 !important; color: #FFFFFF !important; box-shadow: 0 0 10px rgba(16, 185, 129, 0.4) !important; border: 1px solid #10B981 !important; transform: translateY(-1px); }
</style>
""", unsafe_allow_html=True)

st.markdown("<div class='main-header'><h1>LINANCE TERMINAL</h1><p>SYS.CORE // AI QUANTITATIVE ANALYSIS</p></div>", unsafe_allow_html=True)

# ==========================================
# 5. BẢNG ĐIỀU KHIỂN HỆ THỐNG (SIDEBAR)
# ==========================================
with st.sidebar:
    st.markdown("### HỆ THỐNG ĐIỀU KHIỂN")
    st.caption("TRẠNG THÁI: KẾT NỐI API ỔN ĐỊNH")
    if st.button("🔄 CẬP NHẬT DỮ LIỆU"):
        st.cache_data.clear()
        st.rerun()

    st.markdown("---")
    st.markdown("### HỒ SƠ SỨC KHỎE CỔ PHIẾU")
    rpg_ticker = st.text_input("Nhập Mã CK (VD: HPG):", "").upper()
    
    if rpg_ticker:
        if dict_dfs:
            df_rs = dict_dfs.get("RS_DATA", pd.DataFrame())
            df_ta = dict_dfs.get("TA_DATA", pd.DataFrame())
            if not df_rs.empty:
                render_rpg_card(rpg_ticker, df_rs, df_ta)
            else:
                st.warning("Hệ thống cảnh báo: Dữ liệu RS_DATA đang trống.")
        else:
            st.error("Lỗi truy xuất: Chưa tải được dữ liệu hệ thống.")

# ==========================================
# 6. TRUNG TÂM XỬ LÝ CHATBOT AI AGENT
# ==========================================
if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "assistant", "content": "LINANCE CORE ONLINE. Hệ thống đã kích hoạt Lõi Quản trị Vốn (Position Sizing) và Trạm Xuất Bản. Hãy nhập truy vấn của Ngài."}]

# HIỂN THỊ LẠI LỊCH SỬ CHAT VỚI CÁC NÚT ĐIỀU KHIỂN ĐỘC LẬP
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        
        if "chart" in message and message["chart"] is not None:
            st.line_chart(message["chart"])
            
        if message["role"] == "assistant":
            col_btn1, col_btn2, _ = st.columns([1.5, 2, 6])
            with col_btn1:
                components.html(render_copy_button(message["content"]), height=35)
            with col_btn2:
                report_html = generate_professional_report(message["content"])
                ticker_match = re.search(r'\[([A-Z0-9]{3,4})\]', message["content"])
                ticker_name = ticker_match.group(1) if ticker_match else "STOCK"
                file_name = f"LINANCE_{ticker_name}_{datetime.now().strftime('%d%m%Y_%H%M')}.pdf"
                st.download_button(
                    label="📥 EXPORT PDF",
                    data=report_html,
                    file_name=file_name,
                    mime="application/pdf",
                    key=f"dl_btn_{hash(message['content'])}"
                )

if prompt := st.chat_input("Nhập mã CK hoặc truy vấn (VD: Phân tích HPG, NAV 1 tỷ, rủi ro 2%)..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        chart_data_to_save = None 
        
        with st.spinner("ĐANG XỬ LÝ TRUY VẤN VÀ QUẢN TRỊ RỦI RO..."):
            try:
                data_context = ""
                for sheet_name, df_sheet in dict_dfs.items():
                    if not df_sheet.empty:
                        df_clean = df_sheet.copy()
                        for col in df_clean.select_dtypes(include=['float64', 'float32']).columns:
                            df_clean[col] = df_clean[col].round(2)

                        if sheet_name == "RS_DATA":
                            essential_cols = [c for c in ['Mã CK', 'Ngành', 'Giá', 'RS_1M', 'KL_TB_20', 'Đột_Biến_KL', 'Tech_Score', 'Trạng Thái', 'P/E', 'P/B', 'ROE (%)', 'Nợ/Vốn Chủ'] if c in df_clean.columns]
                            if essential_cols: 
                                data_context += f"--- DATASET: {sheet_name} ---\n{df_clean[essential_cols].head(200).to_csv(index=False)}\n\n"
                            else: 
                                data_context += f"--- DATASET: {sheet_name} ---\n{df_clean.head(200).to_csv(index=False)}\n\n"
                                
                        elif sheet_name == "TA_DATA":
                            ta_cols = [c for c in ['Mã CK', 'Giá Hiện Tại', 'Tenkan_sen', 'Kijun_sen', 'Senkou_A', 'Senkou_B', 'Trạng Thái Mây', 'Tín Hiệu Kumo'] if c in df_clean.columns]
                            if ta_cols: 
                                data_context += f"--- DATASET: {sheet_name} ---\n{df_clean[ta_cols].head(200).to_csv(index=False)}\n\n"
                            else: 
                                data_context += f"--- DATASET: {sheet_name} ---\n{df_clean.head(200).to_csv(index=False)}\n\n"
                        else:
                            data_context += f"--- DATASET: {sheet_name} ---\n{df_clean.head(200).to_csv(index=False)}\n\n"

                client = genai.Client(api_key=API_KEY)
                
                sys_prompt = """
                Bạn là Bậc thầy Phân tích Định lượng và Cố vấn Giao dịch cấp tổ chức tại LINANCE Terminal.
                MỤC TIÊU CỐT LÕI: Đưa ra Kế hoạch Giao dịch (Actionable Trading Plan) quyết đoán. Tuyệt đối không nhận định nước đôi.

                NGUYÊN TẮC HOẠT ĐỘNG:
                1. ĐỘT BIẾN KHỐI LƯỢNG LÀ TÍN HIỆU CỐT LÕI: Luôn kiểm tra sự đột biến khối lượng (Đột_Biến_KL hoặc dữ liệu Real-time). Mức độ đột biến > 150% xác nhận dòng tiền lớn (Smart Money).
                2. PHÂN TÍCH KỸ THUẬT & ICHIMOKU: Bắt buộc đối chiếu sự đồng thuận của hệ thống Ichimoku từ bảng TA_DATA để củng cố luận điểm.
                3. QUẢN TRỊ VỐN (POSITION SIZING): NẾU người dùng cung cấp quy mô vốn (NAV) và mức rủi ro chấp nhận (Ví dụ: NAV 1 tỷ, rủi ro 2%), BẮT BUỘC thiết lập hạng mục TỶ TRỌNG ĐI TIỀN. Tính toán rõ số lượng cổ phiếu tối đa được phép mua theo công thức: Số lượng = (NAV * % Rủi ro) / (Giá Mua - Giá Cắt lỗ). Đưa ra con số khối lượng chính xác để bảo vệ tài khoản.
                4. KẾ HOẠCH GIAO DỊCH: BẮT BUỘC trình bày theo cấu trúc: 
                   - LUẬN ĐIỂM ĐẦU TƯ: Sự hội tụ giữa Dòng tiền, Kỹ thuật và Cơ bản.
                   - VÙNG MUA (Entry Range): Dựa vào các mức hỗ trợ cứng của Ichimoku.
                   - ĐIỂM CẮT LỖ CỨNG (Stop-loss): Có giải thích lý do kỹ thuật rõ ràng.
                   - ĐIỂM CHỐT LỜI (Take-profit): Vùng giá mục tiêu kỳ vọng.
                   - TỶ TRỌNG ĐI TIỀN: (Chỉ hiện ra nếu có dữ liệu NAV và Rủi ro).
                   - TỶ LỆ R:R: Tính toán rủi ro/lợi nhuận thực tế.
                5. BÁO CÁO KHUYẾN NGHỊ TỔ CHỨC: Ưu tiên dữ liệu nội bộ. Chỉ gọi công cụ `search_internet` khi thật sự cần thông tin vĩ mô bổ trợ.
                6. KIỂM CHỨNG REAL-TIME: Luôn gọi `get_live_stock_data` để cập nhật giá.
                7. VĂN PHONG VÀ TRÌNH BÀY: Chuyên nghiệp, lạnh lùng, định lượng. Tuyệt đối KHÔNG dùng emoji.
                8. MIỄN TRỪ TRÁCH NHIỆM: Ở cuối câu trả lời luôn chèn chính xác văn bản: "*Miễn trừ trách nhiệm: Kế hoạch giao dịch trên được tổng hợp từ thuật toán định lượng và dữ liệu thị trường hiện hành, nhà đầu tư tự quản trị rủi ro đối với quyết định giải ngân.*"
                """
                
                full_prompt = f"{sys_prompt}\n\nKHO DỮ LIỆU NỘI BỘ:\n{data_context}\n\nTRUY VẤN: {prompt}"
                
                response = client.models.generate_content(
                    model='gemini-3.1-flash-lite', 
                    contents=full_prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.2,
                        tools=[search_internet, get_live_stock_data, draw_technical_chart] 
                    )
                )
                
                if response.function_calls:
                    messages_for_ai = [
                        types.Content(role="user", parts=[types.Part.from_text(full_prompt)]),
                        response.candidates[0].content
                    ]
                    
                    tool_response_parts = []
                    for tool_call in response.function_calls:
                        result_text = ""
                        if tool_call.name == "search_internet":
                            query = tool_call.args.get("query", prompt)
                            result_text = search_internet(query)
                            
                        elif tool_call.name == "get_live_stock_data":
                            ticker = tool_call.args.get("ticker", "")
                            result_text = get_live_stock_data(ticker)
                            
                        elif tool_call.name == "draw_technical_chart":
                            ticker = tool_call.args.get("ticker", "").strip().upper()
                            try:
                                import yfinance as yf
                                yf_ticker = f"{ticker}.VN" if not ticker.endswith(".VN") else ticker
                                stock = yf.Ticker(yf_ticker)
                                hist_data = stock.history(period="6mo")
                                if not hist_data.empty:
                                    chart_df = hist_data[['Close']].copy()
                                    chart_df.rename(columns={'Close': f'Giá {ticker}'}, inplace=True)
                                    chart_df.index = chart_df.index.tz_localize(None) 
                                    chart_data_to_save = chart_df
                                    result_text = "[SYSTEM] Đã nhận được mảng dữ liệu. Hãy trả lời người dùng."
                                else:
                                    result_text = f"[SYSTEM CẢNH BÁO] Không tìm thấy lịch sử giá {ticker}."
                            except Exception as chart_err:
                                result_text = f"[SYSTEM FAULT] Lỗi: {chart_err}"
                                
                        tool_response_parts.append(
                            types.Part.from_function_response(
                                name=tool_call.name, 
                                response={"result": result_text}
                            )
                        )
                    
                    messages_for_ai.append(types.Content(role="user", parts=tool_response_parts))
                    response = client.models.generate_content(
                        model='gemini-3.1-flash-lite',
                        contents=messages_for_ai,
                        config=types.GenerateContentConfig(temperature=0.2)
                    )
            
                if chart_data_to_save is None and ("đồ thị" in prompt.lower() or "biểu đồ" in prompt.lower() or "chart" in prompt.lower()):
                    match = re.search(r'\b[A-Z]{3}\b', prompt.upper())
                    fallback_ticker = match.group(0) if match else (rpg_ticker if rpg_ticker else None)
                    
                    if fallback_ticker:
                        import yfinance as yf
                        try:
                            yf_ticker = f"{fallback_ticker}.VN" if not fallback_ticker.endswith(".VN") else fallback_ticker
                            stock = yf.Ticker(yf_ticker)
                            hist_data = stock.history(period="6mo")
                            if not hist_data.empty:
                                chart_df = hist_data[['Close']].copy()
                                chart_df.rename(columns={'Close': f'Giá {fallback_ticker}'}, inplace=True)
                                chart_df.index = chart_df.index.tz_localize(None)
                                chart_data_to_save = chart_df
                        except:
                            pass

            except Exception as e:
                st.error(f"SYSTEM FAULT: {e}")
                response = None

        # HIỂN THỊ KẾT QUẢ ĐẦU RA AN TOÀN
        if response:
            st.markdown(response.text)
            
            col_btn1, col_btn2, _ = st.columns([1.5, 2, 6])
            with col_btn1:
                components.html(render_copy_button(response.text), height=35)
            with col_btn2:
                report_html = generate_professional_report(response.text)
                ticker_match = re.search(r'\[([A-Z0-9]{3,4})\]', response.text)
                ticker_name = ticker_match.group(1) if ticker_match else "STOCK"
                file_name = f"LINANCE_{ticker_name}_{datetime.now().strftime('%d%m%Y_%H%M')}.pdf"
                st.download_button(
                    label="EXPORT PDF",
                    data=report_html,
                    file_name=file_name,
                    mime="application/pdf",
                    key=f"dl_btn_{hash(response.text)}"
                )
            
            if chart_data_to_save is not None:
                st.line_chart(chart_data_to_save)
                
            new_msg = {"role": "assistant", "content": response.text}
            if chart_data_to_save is not None:
                new_msg["chart"] = chart_data_to_save
            st.session_state.messages.append(new_msg)
